server:
  port: 8081
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.aula-spring
      routing-key:
        producer: rk.producer.aula-spring
      deadletter:
        producer: dl.producer.aula-spring
        
# docker run -d --name rabbitmq -p 15672:15672 -p 5672:5672 rabbitmq:3-management